"""Initial migration

Revision ID: 44a4c89fd574
Revises: 
Create Date: 2026-01-01 20:18:13.849479

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '44a4c89fd574'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('src', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('annex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Enum('EAZY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('MISC', 'CRYPTO', 'WEB', 'REVERSE', 'PWN', name='tasktype'), nullable=False),
    sa.Column('solve_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_task_name'), 'task', ['task_name'], unique=True)
    
    # Moved user creation up
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_answer_time', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    # Removed FK to team here
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('allow_join', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_team_name'), 'team', ['team_name'], unique=True)
    
    # Add FK to user for team_id
    op.create_foreign_key('fk_user_team', 'user', 'team', ['team_id'], ['id'])

    op.create_table('answerrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('answer_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firstkill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('answer_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('msg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('msg_type', sa.Enum('OTHER', 'CHAT', 'SYSTEM', 'APPLICATION', 'INVITATION', 'KICKOUT', name='messagetype'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['origin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('firstkill')
    op.drop_table('answerrecord')
    op.drop_constraint('fk_user_team', 'user', type_='foreignkey')
    op.drop_index(op.f('ix_team_team_name'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_task_task_name'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
